# Generated by Django 3.0.9 on 2020-09-28 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(default='---', max_length=40)),
                ('bounding_boxes', models.CharField(default='---', max_length=300)),
            ],
        ),
    ]
