# Generated by Django 3.0.9 on 2020-09-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_twitter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filtro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(blank=True)),
                ('fecha_fin', models.DateTimeField(blank=True)),
                ('hashtag', models.CharField(default='---', max_length=100)),
                ('num_hashtags', models.IntegerField()),
                ('mencions', models.CharField(default='---', max_length=100)),
                ('num_mencions', models.IntegerField()),
                ('keywords', models.CharField(default='---', max_length=150)),
                ('username', models.CharField(default='---', max_length=150)),
                ('fecha_min_creation_user', models.DateTimeField(blank=True)),
                ('fecha_max_creation_user', models.DateTimeField(blank=True)),
                ('username_mencion', models.CharField(default='---', max_length=150)),
                ('min_followers', models.IntegerField()),
                ('min_friends', models.IntegerField()),
                ('country', models.CharField(default='---', max_length=40)),
                ('len_min_tweet', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True)),
                ('username', models.CharField(default='---', max_length=80)),
                ('texto', models.CharField(default='---', max_length=150)),
                ('num_mencions', models.IntegerField()),
                ('num_hashtags', models.IntegerField()),
                ('longuitud', models.IntegerField()),
                ('country', models.CharField(default='---', max_length=40)),
            ],
        ),
    ]
