# Generated by Django 3.0.9 on 2020-10-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_twitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtro',
            name='country',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='filtro',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filtro',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filtro',
            name='fecha_max_creation_user',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filtro',
            name='fecha_min_creation_user',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filtro',
            name='hashtags',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='filtro',
            name='keywords',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='filtro',
            name='language',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='filtro',
            name='mencions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='filtro',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
