# Generated by Django 3.0.9 on 2020-09-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_twitter', '0002_filtro_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtro',
            name='country',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='filtro',
            name='fecha_fin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='filtro',
            name='fecha_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='filtro',
            name='fecha_max_creation_user',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='filtro',
            name='fecha_min_creation_user',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='filtro',
            name='hashtag',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='filtro',
            name='keywords',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='filtro',
            name='len_min_tweet',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='filtro',
            name='mencions',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='filtro',
            name='min_followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='filtro',
            name='min_friends',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='filtro',
            name='num_hashtags',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='filtro',
            name='num_mencions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='filtro',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='filtro',
            name='username_mencion',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='longuitud',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='num_hashtags',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='num_mencions',
            field=models.IntegerField(default=0),
        ),
    ]
