# Generated by Django 3.0.9 on 2020-09-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_twitter', '0003_auto_20200930_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='bounding_boxes',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='country',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='texto',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='username',
            field=models.CharField(max_length=80),
        ),
    ]
