# Generated by Django 3.0.9 on 2020-09-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_twitter', '0004_auto_20200930_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtro',
            name='from_count',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='filtro',
            name='language',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='filtro',
            name='min_faves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='filtro',
            name='min_replies',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='filtro',
            name='min_retweets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='filtro',
            name='min_followers',
            field=models.IntegerField(),
        ),
    ]
