# Generated by Django 3.0.9 on 2020-09-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_twitter', '0005_auto_20200930_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtro',
            name='fecha_fin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='filtro',
            name='fecha_inicio',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='filtro',
            name='fecha_max_creation_user',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='filtro',
            name='fecha_min_creation_user',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='filtro',
            name='hashtag',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='filtro',
            name='min_followers',
            field=models.IntegerField(default=0),
        ),
    ]
