# Generated by Django 3.0.9 on 2020-09-30 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_twitter', '0006_auto_20200930_0207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filtro',
            old_name='hashtag',
            new_name='hashtags',
        ),
    ]
