# Generated by Django 3.0.9 on 2020-09-30 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_twitter', '0007_auto_20200930_0211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filtro',
            old_name='num_hashtags',
            new_name='min_hashtags',
        ),
        migrations.RenameField(
            model_name='filtro',
            old_name='num_mencions',
            new_name='min_mencions',
        ),
        migrations.RemoveField(
            model_name='filtro',
            name='from_count',
        ),
        migrations.RemoveField(
            model_name='filtro',
            name='username_mencion',
        ),
    ]
